package gametictac;


import gametictac.GameTicTAC;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author joshiyogesh
 */
public class TicTacToe extends javax.swing.JFrame {

    /**
     * Creates new form TicTacToe
     * 
     */
    public static String b1="Y" ,b2="Y" ,b3="Y" ,b4="Y" ,b5="Y" ,b6="Y" ,b7="Y" ,b8="Y" ,b9="Y" ;
    public TicTacToe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gametictac/Search-icon.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.darkShadow"));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gametictac/Search-icon.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gametictac/Search-icon.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gametictac/Search-icon.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gametictac/Search-icon.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gametictac/Search-icon.png"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gametictac/Search-icon.png"))); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gametictac/Search-icon.png"))); // NOI18N
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gametictac/Search-icon.png"))); // NOI18N
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(219, 28, 28));
        jLabel1.setText("Player One");

        jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(208, 22, 22));
        jLabel2.setText("Player Two");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addComponent(jButton4)
                    .addComponent(jButton7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton9))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton6)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4)
                    .addComponent(jButton5)
                    .addComponent(jButton6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton8)
                    .addComponent(jButton9)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(GameTicTAC.playerOneTurn == true ){
            b1 = "X" ;
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gametictac/x-icon.png"))); // NOI18N
        GameTicTAC.checkForWin();
        GameTicTAC.playerOneTurn = false ;
        }
        else{
            b1 = "O" ;
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gametictac/Letter-O-icon.png"))); // NOI18N
        GameTicTAC.checkForWin();
        GameTicTAC.playerOneTurn = true ;
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
          if(GameTicTAC.playerOneTurn == true ){
              b2 = "X";
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gametictac/x-icon.png"))); // NOI18N
        GameTicTAC.checkForWin();
        GameTicTAC.playerOneTurn = false ;
        }
        else{
              b2 = "O";
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gametictac/Letter-O-icon.png"))); // NOI18N
        GameTicTAC.checkForWin();
        GameTicTAC.playerOneTurn = true ;
        }
         
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
          if(GameTicTAC.playerOneTurn == true ){
              b3 = "X" ;
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gametictac/x-icon.png"))); // NOI18N
        GameTicTAC.checkForWin();
        GameTicTAC.playerOneTurn = false ;
        }
        else{
              b3 = "O" ;
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gametictac/Letter-O-icon.png"))); // NOI18N
        GameTicTAC.checkForWin();
        GameTicTAC.playerOneTurn = true ;
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
          if(GameTicTAC.playerOneTurn == true ){
              b4 = "X" ;
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gametictac/x-icon.png"))); // NOI18N
        GameTicTAC.checkForWin();
        GameTicTAC.playerOneTurn = false ;
        }
        else{
              b4 = "O" ;
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gametictac/Letter-O-icon.png"))); // NOI18N
        GameTicTAC.checkForWin();
        GameTicTAC.playerOneTurn = true ;
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
          if(GameTicTAC.playerOneTurn == true ){
              b5 = "X" ;
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gametictac/x-icon.png"))); // NOI18N
        GameTicTAC.checkForWin();
        GameTicTAC.playerOneTurn = false ;
        }
        else{
              b5 = "O" ;
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gametictac/Letter-O-icon.png"))); // NOI18N
        GameTicTAC.checkForWin();
        GameTicTAC.playerOneTurn = true ;
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        b6 = "X" ;
          if(GameTicTAC.playerOneTurn == true ){
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gametictac/x-icon.png"))); // NOI18N
        GameTicTAC.checkForWin();
        GameTicTAC.playerOneTurn = false ;
        }
        else{
              b6 = "O" ;
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gametictac/Letter-O-icon.png"))); // NOI18N
        GameTicTAC.checkForWin();
        GameTicTAC.playerOneTurn = true ;
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
          if(GameTicTAC.playerOneTurn == true ){
              b7 = "X" ;
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gametictac/x-icon.png"))); // NOI18N
        GameTicTAC.checkForWin();
        GameTicTAC.playerOneTurn = false ;
        }
        else{
              b7 = "O" ;
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gametictac/Letter-O-icon.png"))); // NOI18N
        GameTicTAC.checkForWin();
        GameTicTAC.playerOneTurn = true ;
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
          if(GameTicTAC.playerOneTurn == true ){
              b8 = "X" ;
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gametictac/x-icon.png"))); // NOI18N
        GameTicTAC.checkForWin();
        GameTicTAC.playerOneTurn = false ;
        }
        else{
              b8 = "O" ;
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gametictac/Letter-O-icon.png"))); // NOI18N
        GameTicTAC.checkForWin();
        GameTicTAC.playerOneTurn = true ;
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
          if(GameTicTAC.playerOneTurn == true ){
              b9 = "X" ;
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gametictac/x-icon.png"))); // NOI18N
        GameTicTAC.checkForWin();
        GameTicTAC.playerOneTurn = false ;
        }
        else{
              b9 = "O" ;
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gametictac/Letter-O-icon.png"))); // NOI18N
        GameTicTAC.checkForWin();
        GameTicTAC.playerOneTurn = true ;
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TicTacToe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TicTacToe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TicTacToe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TicTacToe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TicTacToe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
